// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/mail_register.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailRegisterRequest) Reset() {
	*x = MailRegisterRequest{}
	mi := &file_proto_mail_register_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailRegisterRequest) ProtoMessage() {}

func (x *MailRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_register_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailRegisterRequest.ProtoReflect.Descriptor instead.
func (*MailRegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_register_proto_rawDescGZIP(), []int{0}
}

func (x *MailRegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type MailRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailRegisterResponse) Reset() {
	*x = MailRegisterResponse{}
	mi := &file_proto_mail_register_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailRegisterResponse) ProtoMessage() {}

func (x *MailRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_register_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailRegisterResponse.ProtoReflect.Descriptor instead.
func (*MailRegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_mail_register_proto_rawDescGZIP(), []int{1}
}

func (x *MailRegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_mail_register_proto protoreflect.FileDescriptor

const file_proto_mail_register_proto_rawDesc = "" +
	"\n" +
	"\x19proto/mail_register.proto\x12\x05proto\"+\n" +
	"\x13MailRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"0\n" +
	"\x14MailRegisterResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\x0fZ\rbackend/protob\x06proto3"

var (
	file_proto_mail_register_proto_rawDescOnce sync.Once
	file_proto_mail_register_proto_rawDescData []byte
)

func file_proto_mail_register_proto_rawDescGZIP() []byte {
	file_proto_mail_register_proto_rawDescOnce.Do(func() {
		file_proto_mail_register_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mail_register_proto_rawDesc), len(file_proto_mail_register_proto_rawDesc)))
	})
	return file_proto_mail_register_proto_rawDescData
}

var file_proto_mail_register_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_mail_register_proto_goTypes = []any{
	(*MailRegisterRequest)(nil),  // 0: proto.MailRegisterRequest
	(*MailRegisterResponse)(nil), // 1: proto.MailRegisterResponse
}
var file_proto_mail_register_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mail_register_proto_init() }
func file_proto_mail_register_proto_init() {
	if File_proto_mail_register_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mail_register_proto_rawDesc), len(file_proto_mail_register_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mail_register_proto_goTypes,
		DependencyIndexes: file_proto_mail_register_proto_depIdxs,
		MessageInfos:      file_proto_mail_register_proto_msgTypes,
	}.Build()
	File_proto_mail_register_proto = out.File
	file_proto_mail_register_proto_goTypes = nil
	file_proto_mail_register_proto_depIdxs = nil
}
